/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "rgba(var(--color-surface-container-high), <alpha-value>)",
        "tertiary-container": "rgba(var(--color-tertiary-container), <alpha-value>)",
        "on-error-container": "rgba(var(--color-on-error-container), <alpha-value>)",
        "on-secondary-fixed": "rgba(var(--color-on-secondary-fixed), <alpha-value>)",
        "inverse-primary": "rgba(var(--color-inverse-primary), <alpha-value>)",
        "secondary": "rgba(var(--color-secondary), <alpha-value>)",
        "on-primary-fixed-variant": "rgba(var(--color-on-primary-fixed-variant), <alpha-value>)",
        "surface-container": "rgba(var(--color-surface-container), <alpha-value>)",
        "on-tertiary-container": "rgba(var(--color-on-tertiary-container), <alpha-value>)",
        "secondary-fixed": "rgba(var(--color-secondary-fixed), <alpha-value>)",
        "tertiary-fixed": "rgba(var(--color-tertiary-fixed), <alpha-value>)",
        "on-primary-container": "rgba(var(--color-on-primary-container), <alpha-value>)",
        "surface-container-highest": "rgba(var(--color-surface-container-highest), <alpha-value>)",
        "on-primary": "rgba(var(--color-on-primary), <alpha-value>)",
        "surface-container-lowest": "rgba(var(--color-surface-container-lowest), <alpha-value>)",
        "secondary-fixed-dim": "rgba(var(--color-secondary-fixed-dim), <alpha-value>)",
        "primary-dark": "rgba(var(--color-primary-dark), <alpha-value>)",
        "success": "rgba(var(--color-success), <alpha-value>)",
        "on-tertiary": "rgba(var(--color-on-tertiary), <alpha-value>)",
        "surface-bright": "rgba(var(--color-surface-bright), <alpha-value>)",
        "secondary-container": "rgba(var(--color-secondary-container), <alpha-value>)",
        "surface-dim": "rgba(var(--color-surface-dim), <alpha-value>)",
        "on-surface": "rgba(var(--color-on-surface), <alpha-value>)",
        "on-tertiary-fixed-variant": "rgba(var(--color-on-tertiary-fixed-variant), <alpha-value>)",
        "danger": "rgba(var(--color-danger), <alpha-value>)",
        "inverse-surface": "rgba(var(--color-inverse-surface), <alpha-value>)",
        "primary-fixed-dim": "rgba(var(--color-primary-fixed-dim), <alpha-value>)",
        "on-secondary-fixed-variant": "rgba(var(--color-on-secondary-fixed-variant), <alpha-value>)",
        "primary-fixed": "rgba(var(--color-primary-fixed), <alpha-value>)",
        "on-background": "rgba(var(--color-on-background), <alpha-value>)",
        "inverse-on-surface": "rgba(var(--color-inverse-on-surface), <alpha-value>)",
        "on-error": "rgba(var(--color-on-error), <alpha-value>)",
        "on-primary-fixed": "rgba(var(--color-on-primary-fixed), <alpha-value>)",
        "outline-variant": "rgba(var(--color-outline-variant), <alpha-value>)",
        "surface": "rgba(var(--color-surface), <alpha-value>)",
        "background": "rgba(var(--color-background), <alpha-value>)",
        "surface-variant": "rgba(var(--color-surface-variant), <alpha-value>)",
        "background-blue": "rgba(var(--color-background-blue), <alpha-value>)",
        "surface-container-low": "rgba(var(--color-surface-container-low), <alpha-value>)",
        "primary-light": "rgba(var(--color-primary-light), <alpha-value>)",
        "error-container": "rgba(var(--color-error-container), <alpha-value>)",
        "primary": "rgba(var(--color-primary), <alpha-value>)",
        "warning": "rgba(var(--color-warning), <alpha-value>)",
        "on-surface-variant": "rgba(var(--color-on-surface-variant), <alpha-value>)",
        "primary-container": "rgba(var(--color-primary-container), <alpha-value>)",
        "on-secondary": "rgba(var(--color-on-secondary), <alpha-value>)",
        "on-secondary-container": "rgba(var(--color-on-secondary-container), <alpha-value>)",
        "error": "rgba(var(--color-error), <alpha-value>)",
        "on-tertiary-fixed": "rgba(var(--color-on-tertiary-fixed), <alpha-value>)",
        "tertiary": "rgba(var(--color-tertiary), <alpha-value>)",
        "text-muted": "rgba(var(--color-text-muted), <alpha-value>)",
        "tertiary-fixed-dim": "rgba(var(--color-tertiary-fixed-dim), <alpha-value>)",
        "outline": "rgba(var(--color-outline), <alpha-value>)",
        "surface-tint": "rgba(var(--color-surface-tint), <alpha-value>)",
        "button-primary": "rgba(var(--color-button-primary), <alpha-value>)",
        "border-subtle": "rgba(var(--color-border-subtle), <alpha-value>)",
        "surface-glass": "rgba(var(--color-surface-glass), <alpha-value>)",
        "accent-blue": "rgba(var(--color-accent-blue), <alpha-value>)",
        "text-secondary": "rgba(var(--color-text-secondary), <alpha-value>)",
        "surface-elevated": "rgba(var(--color-surface-elevated), <alpha-value>)",
        "success-muted": "rgba(var(--color-success-muted), <alpha-value>)",
        "surface-main": "rgba(var(--color-surface-main), <alpha-value>)",
        "text-primary": "rgba(var(--color-text-primary), <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Outfit", "Inter", "sans-serif"],
        display: ["Outfit", "sans-serif"],
        tech: ["Space Grotesk", "monospace"],
        mono: ["Space Grotesk", "monospace"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h1": ["52px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-mobile": ["42px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "h2-mobile": ["30px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "h2": ["40px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      spacing: {
        "section-md": "80px",
        "section-lg": "120px",
        "gutter": "24px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        floatSlow: {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-14px) rotate(2deg)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease forwards",
        "fade-in": "fadeIn 0.5s ease forwards",
        "marquee": "marquee 25s linear infinite",
        "float": "float 4s ease-in-out infinite",
        "float-slow": "floatSlow 7s ease-in-out infinite",
        "shimmer": "shimmer 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
